language: python
python:
  - "3.4"
# command to run tests
install:
  - pip install coveralls
script:
  - coverage run -p --source=parrot.py -m unittest discover
after_success:
  - coverage combine
  - coveralls
